<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>zig</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~Z</string>
	<key>name</key>
	<string>Zig</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#dummy_main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z_][\w.]*|@\".+\")?\s*(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.zig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.braces.begin.zig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.braces.end.zig</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dummy_main</string>
				</dict>
			</array>
		</dict>
		<key>character_escapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\n</string>
					<key>name</key>
					<string>constant.character.escape.newline.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\r</string>
					<key>name</key>
					<string>constant.character.escape.carrigereturn.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\t</string>
					<key>name</key>
					<string>constant.character.escape.tabulator.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\\</string>
					<key>name</key>
					<string>constant.character.escape.backslash.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\'</string>
					<key>name</key>
					<string>constant.character.escape.single-quote.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\"</string>
					<key>name</key>
					<string>constant.character.escape.double-quote.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\x[a-fA-F\d]{2}</string>
					<key>name</key>
					<string>constant.character.escape.hexidecimal.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\u\{[a-fA-F\d]{1,6}\}</string>
					<key>name</key>
					<string>constant.character.escape.hexidecimal.zig</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>///</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.documentation.zig</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//[^/]\s*TODO</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.todo.zig</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//[^/]*</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.zig</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(null|undefined|true|false)\b</string>
					<key>name</key>
					<string>constant.language.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;!\.)(-?[\d_]+)(?!\.)\b</string>
					<key>name</key>
					<string>constant.numeric.integer.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;!\.)(0x[a-fA-F\d_]+)(?!\.)\b</string>
					<key>name</key>
					<string>constant.numeric.integer.hexadecimal.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;!\.)(0o[0-7_]+)(?!\.)\b</string>
					<key>name</key>
					<string>constant.numeric.integer.octal.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;!\.)(0b[01_]+)(?!\.)\b</string>
					<key>name</key>
					<string>constant.numeric.integer.binary.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\.)(-?\b[\d_]+(?:\.[\d_]+)?(?:[eE][+-]?[\d_]+)?)(?!\.)\b</string>
					<key>name</key>
					<string>constant.numeric.float.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\.)(-?\b0x[a-fA-F\d_]+(?:\.[a-fA-F\d_]+)?[pP]?(?:[+-]?[\d_]+)?)(?!\.)\b</string>
					<key>name</key>
					<string>constant.numeric.float.hexadecimal.zig</string>
				</dict>
			</array>
		</dict>
		<key>container_decl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?!\d)([a-zA-Z_]\w*|@\".+\")?(?=\s*=\s*(?:extern|packed)?\b\s*(?:union)\s*[(\{])</string>
					<key>name</key>
					<string>entity.name.union.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?!\d)([a-zA-Z_]\w*|@\".+\")?(?=\s*=\s*(?:extern|packed)?\b\s*(?:struct)\s*[(\{])</string>
					<key>name</key>
					<string>entity.name.struct.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?!\d)([a-zA-Z_]\w*|@\".+\")?(?=\s*=\s*(?:extern|packed)?\b\s*(?:enum)\s*[(\{])</string>
					<key>name</key>
					<string>entity.name.enum.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?!\d)([a-zA-Z_]\w*|@\".+\")?(?=\s*=\s*(?:error)\s*[(\{])</string>
					<key>name</key>
					<string>entity.name.error.zig</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.error.zig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.accessor.zig</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.error.zig</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(error)(\.)([a-zA-Z_]\w*|@\".+\")</string>
				</dict>
			</array>
		</dict>
		<key>dummy_main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storage_modifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#container_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storage</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#support</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#field_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_def</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum_literal</string>
				</dict>
			</array>
		</dict>
		<key>enum_literal</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\)|\?|\}|\]|\*)(\.(?:[a-zA-Z_]\w*\b|@\"[^\"]*\"))(?!\(|\s*=[^=&gt;])</string>
			<key>name</key>
			<string>constant.language.enum</string>
		</dict>
		<key>field_decl</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z_]\w*|@\".+\")\s*(:)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.member.zig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.zig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([a-zA-Z_][\w.]*|@\".+\")?\s*(?:(,)|(=)|$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.zig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.zig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.zig</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dummy_main</string>
				</dict>
			</array>
		</dict>
		<key>function_call</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!fn)\b([a-zA-Z_]\w*|@\".+\")(?=\s*\()</string>
			<key>name</key>
			<string>variable.function.zig</string>
		</dict>
		<key>function_def</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=fn)\s+([a-zA-Z_]\w*|@\".+\")(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.begin.zig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\)[^\)])\s*([a-zA-Z_][\w.]*|@\".+\")?(!)?\s*(?:([a-zA-Z_][\w.]*|@\".+\")\b(?!\s*\())?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.zig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.zig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.zig</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#param_list</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([a-zA-Z_][\w.]*|@\".+\")</string>
					<key>name</key>
					<string>storage.type.zig</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dummy_main</string>
				</dict>
			</array>
		</dict>
		<key>function_type</key>
		<dict>
			<key>begin</key>
			<string>\b(fn)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.zig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.begin.zig</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.function.parameters.zig</string>
			<key>end</key>
			<string>(?&lt;=\)|\})\s*([a-zA-Z_][\w.]*|@\".+\")?\s*(!)?\s*([a-zA-Z_][\w.]*|@\".+\")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.zig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.zig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.zig</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#param_list</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([a-zA-Z_][\w.]*|@\".+\")</string>
					<key>name</key>
					<string>storage.type.zig</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dummy_main</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(while|for|break|return|continue|asm|defer|errdefer|unreachable)\b</string>
					<key>name</key>
					<string>keyword.control.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(async|await|suspend|nosuspend|resume)\b</string>
					<key>name</key>
					<string>keyword.control.async.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(if|else|switch|try|catch|orelse)\b</string>
					<key>name</key>
					<string>keyword.control.conditional.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)(@import|@cImport|@cInclude)\b</string>
					<key>name</key>
					<string>keyword.control.import.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(usingnamespace)\b</string>
					<key>name</key>
					<string>keyword.other.usingnamespace.zig</string>
				</dict>
			</array>
		</dict>
		<key>label</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.zig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.label.zig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.label.zig</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(break|continue)\s*:\s*([a-zA-Z_]\w*|@\".+\")\b|\b(?!\d)([a-zA-Z_]\w*|@\".+\")\b(?=\s*:\s*(?:\{|while\b))</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b!\b</string>
					<key>name</key>
					<string>keyword.operator.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|(?:!|&gt;|&lt;)=?)</string>
					<key>name</key>
					<string>keyword.operator.logical.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(and|or)\b</string>
					<key>name</key>
					<string>keyword.operator.word.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?:(?:\+|-|\*)\%?|/|%|&lt;&lt;|&gt;&gt;|&amp;|\|(?=[^\|])|\^)?=)</string>
					<key>name</key>
					<string>keyword.operator.assignment.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?:\+|-|\*)\%?|/(?!/)|%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&lt;&lt;|&gt;&gt;|&amp;(?=[a-zA-Z_]|@\")|\|(?=[^\|])|\^|~)</string>
					<key>name</key>
					<string>keyword.operator.bitwise.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\+\+|\*\*|-&gt;|\.\?|\.\*|&amp;(?=[a-zA-Z_]|@\")|\?|\|\||\.{2,3})</string>
					<key>name</key>
					<string>keyword.operator.other.zig</string>
				</dict>
			</array>
		</dict>
		<key>param_list</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z_]\w*|@\".+\")\s*(:)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.zig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.zig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([a-zA-Z_][\w.]*|@\".+\")?\s*(?:(,)|(\)))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.zig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.zig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.end.zig</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dummy_main</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([a-zA-Z_][\w.]*|@\".+\")</string>
					<key>name</key>
					<string>storage.type.zig</string>
				</dict>
			</array>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.terminator.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\()</string>
					<key>name</key>
					<string>punctuation.section.parens.begin.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\))</string>
					<key>name</key>
					<string>punctuation.section.parens.end.zig</string>
				</dict>
			</array>
		</dict>
		<key>storage</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(bool|void|noreturn|type|anyerror|anytype)\b</string>
					<key>name</key>
					<string>storage.type.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;!\.)([iu]\d+|[iu]size|comptime_int)\b</string>
					<key>name</key>
					<string>storage.type.integer.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(f16|f32|f64|f128|comptime_float)\b</string>
					<key>name</key>
					<string>storage.type.float.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(c_short|c_ushort|c_int|c_uint|c_long|c_ulong|c_longlong|c_ulonglong|c_longdouble|c_void)\b</string>
					<key>name</key>
					<string>storage.type.c_compat.zig</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.zig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.zig</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.zig</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(anyframe)\b\s*(-&gt;)?\s*(?:([a-zA-Z_][\w.]*|@\".+\")\b(?!\s*\())?</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bfn\b</string>
					<key>name</key>
					<string>storage.type.function.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\btest\b</string>
					<key>name</key>
					<string>storage.type.test.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bstruct\b</string>
					<key>name</key>
					<string>storage.type.struct.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\benum\b</string>
					<key>name</key>
					<string>storage.type.enum.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bunion\b</string>
					<key>name</key>
					<string>storage.type.union.zig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\berror\b</string>
					<key>name</key>
					<string>storage.type.error.zig</string>
				</dict>
			</array>
		</dict>
		<key>storage_modifier</key>
		<dict>
			<key>match</key>
			<string>\b(const|var|extern|packed|export|pub|noalias|inline|noinline|comptime|volatile|align|linksection|threadlocal|allowzero)\b</string>
			<key>name</key>
			<string>storage.modifier.zig</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\'</string>
					<key>end</key>
					<string>\'</string>
					<key>name</key>
					<string>string.quoted.single.zig</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#character_escapes</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\[^\'][^\']*?</string>
							<key>name</key>
							<string>invalid.illegal.character.zig</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>c?\"</string>
					<key>end</key>
					<string>\"</string>
					<key>name</key>
					<string>string.quoted.double.zig</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#character_escapes</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\[^\'][^\']*?</string>
							<key>name</key>
							<string>invalid.illegal.character.zig</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>c?\\\\</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>string.quoted.other.zig</string>
				</dict>
			</array>
		</dict>
		<key>support</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w)@[^\"\d][a-zA-Z_]\w*\b</string>
			<key>name</key>
			<string>support.function.zig</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.zig</string>
	<key>uuid</key>
	<string>06C2FF99-3080-441A-9019-460C51E93116</string>
</dict>
</plist>
