files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /common-ui/src/main/res/values/strings.xml
    translation: /common-ui/src/main/res/values-%android_code%/%original_file_name%
  - source: /feature-editor/impl/src/main/res/values/strings.xml
    translation: /feature-editor/impl/src/main/res/values-%android_code%/%original_file_name%
  - source: /feature-explorer/impl/src/main/res/values/strings.xml
    translation: /feature-explorer/impl/src/main/res/values-%android_code%/%original_file_name%
  - source: /feature-fonts/impl/src/main/res/values/strings.xml
    translation: /feature-fonts/impl/src/main/res/values-%android_code%/%original_file_name%
  - source: /feature-git/impl/src/main/res/values/strings.xml
    translation: /feature-git/impl/src/main/res/values-%android_code%/%original_file_name%
  - source: /feature-servers/impl/src/main/res/values/strings.xml
    translation: /feature-servers/impl/src/main/res/values-%android_code%/%original_file_name%
  - source: /feature-settings/impl/src/main/res/values/strings.xml
    translation: /feature-settings/impl/src/main/res/values-%android_code%/%original_file_name%
  - source: /feature-shortcuts/impl/src/main/res/values/strings.xml
    translation: /feature-shortcuts/impl/src/main/res/values-%android_code%/%original_file_name%
  - source: /feature-themes/impl/src/main/res/values/strings.xml
    translation: /feature-themes/impl/src/main/res/values-%android_code%/%original_file_name%
  - source: /fastlane/metadata/android/en-US/full_description.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
  - source: /fastlane/metadata/android/en-US/short_description.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
  - source: /fastlane/metadata/android/en-US/title.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%